### ISSUE TITLE
Not predefined variable $Code

### ISSUE THREAD

**Issue by wikiyu** [dartiss/draft-list#64]
Hey

My issue is:
`2022/06/21 08:19:51 [error] 21441#21441: *2242291 FastCGI sent in stderr: "PHP message: PHP Warning: Undefined variable $code in /PATHblog/wp-content/plugins/simple-draft-list/inc/create-lists.php on line 241" while reading upstream, client: [[IP]], server: [[MYDOMAIN]], request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.0-fpm.sock:", host: "[[MYDOMAIN]]"
`

Could you please check it? 
For me it was enough to add 
$code = ""; 
in line 75 of INC/Create-list.php 

i`m not sure if it is a proper way but it worked and i dont have this error in logs for each site recreation.

**Comment by dartiss** [comment]
Implemented in #68
